# Generated by Django 4.1 on 2022-08-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economic_groups', '0001_initial'),
        ('funds', '0001_initial'),
        ('functions', '0001_initial'),
        ('mdas', '0001_initial'),
        ('economic_items', '0001_initial'),
        ('programmes', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr_prev', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('actual_prev', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('proposed_curr', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('proposed_next', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('jan_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('feb_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('april_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('may_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('june_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('july_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('aug_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('sept_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('oct_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('nov_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('dec_returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('admin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdas.mda')),
                ('eco_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_groups.economic_group')),
                ('func_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.function')),
                ('fund_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('ipsas_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_items.economic_item')),
                ('loc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('prog_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme')),
            ],
        ),
    ]
