# Generated by Django 4.1 on 2023-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='programmeCode',
            field=models.CharField(default='000000000000', max_length=300),
            preserve_default=False,
        ),
    ]
