# Generated by Django 4.1 on 2023-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(default='000000000000', max_length=12)),
                ('sector_name', models.CharField(max_length=200)),
            ],
        ),
    ]
