# Generated by Django 4.1 on 2023-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=8)),
            ],
        ),
    ]
