# Generated by Django 4.1 on 2023-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalReceiptdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminCode', models.CharField(max_length=12)),
                ('adminName', models.CharField(max_length=200)),
                ('ipsasCode', models.CharField(max_length=8)),
                ('ecoName', models.CharField(max_length=300)),
                ('fundCode', models.CharField(max_length=5)),
                ('fundName', models.CharField(max_length=200)),
                ('appr', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('prop', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
            ],
        ),
    ]
