# Generated by Django 3.0.7 on 2020-06-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsectors', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(max_length=12)),
                ('mda_name', models.CharField(max_length=255)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectors.Sector')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subsectors.Subsector')),
            ],
        ),
    ]
