# Generated by Django 4.1 on 2022-08-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displaydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminCode', models.CharField(max_length=12)),
                ('adminName', models.CharField(max_length=200)),
                ('sectorCode', models.CharField(max_length=12)),
                ('sectorName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(max_length=12)),
                ('mda_name', models.CharField(max_length=255)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectors.sector')),
            ],
        ),
    ]
