# Generated by Django 4.1 on 2022-08-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_groups.fund_group')),
            ],
        ),
    ]
