# Generated by Django 4.1 on 2023-01-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economic_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economic_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipsas_code', models.CharField(max_length=8, unique=True)),
                ('ipsas_title', models.CharField(max_length=255)),
                ('eco_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_groups.economic_group')),
            ],
        ),
    ]
