# Generated by Django 3.0.7 on 2020-06-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_groups', '0002_auto_20200627_1444'),
        ('economic_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic_item',
            name='eco_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='economic_groups.Economic_Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='economic_item',
            name='ipsas_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
