# Generated by Django 4.1 on 2023-01-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rev_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipsas_code', models.CharField(max_length=8)),
                ('ipsas_title', models.CharField(max_length=300)),
                ('eco_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rev_groups.rev_group')),
            ],
        ),
    ]
