# Generated by Django 3.0.7 on 2020-06-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        ('sal_structures', '0001_initial'),
        ('ranks', '0001_initial'),
        ('mdas', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr_num_staff', models.IntegerField()),
                ('actual_num_staff', models.IntegerField()),
                ('prop_num_staff', models.IntegerField()),
                ('departments_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='departments.Department')),
                ('mdas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdas.Mda')),
                ('rank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ranks.Rank')),
                ('sal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sal_structures.Sal_Structure')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sectors.Sector')),
            ],
        ),
    ]
