# Generated by Django 4.1 on 2022-08-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='april_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='aug_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='dec_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='feb_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='jan_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='july_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='june_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='may_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='nov_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='oct_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='personnels',
            name='sept_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
    ]
