# Generated by Django 4.1 on 2023-01-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personneldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progCode', models.CharField(max_length=2)),
                ('progName', models.CharField(max_length=500)),
                ('adminCode', models.CharField(max_length=12)),
                ('adminName', models.CharField(max_length=200)),
                ('ipsasCode', models.CharField(max_length=8)),
                ('ecoName', models.CharField(max_length=300)),
                ('funcCode', models.CharField(max_length=5)),
                ('funcName', models.CharField(max_length=200)),
                ('locCode', models.CharField(max_length=8)),
                ('locName', models.CharField(max_length=200)),
                ('fundCode', models.CharField(max_length=5)),
                ('fundName', models.CharField(max_length=200)),
                ('appr', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('prop', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
            ],
        ),
    ]
