# Generated by Django 4.1 on 2023-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sal_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_type', models.CharField(max_length=200)),
                ('basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('meal', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('furniture', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('hazard', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('shift_call', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('medical', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('domestic', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('entertainment', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('exam', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('learned', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('teach', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('leave_grant', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('personnel_assistant', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('news_paper', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('vehicle', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('dta', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('responsibility', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('wardrope', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
            ],
        ),
    ]
