# Generated by Django 3.0.7 on 2020-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='april_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='aug_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='dec_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='feb_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='jan_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='july_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='june_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='may_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='nov_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='oct_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sept_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
    ]
