# Generated by Django 3.0.7 on 2020-06-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economic_groups', '0001_initial'),
        ('mdas', '0001_initial'),
        ('economic_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr_prev', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('actual_prev', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('proposed_curr', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('proposed_next', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('admin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdas.Mda')),
                ('eco_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_groups.Economic_Group')),
                ('ipsas_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economic_items.Economic_Item')),
            ],
        ),
    ]
