# Generated by Django 4.1 on 2022-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economic_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_code', models.CharField(max_length=8, unique=True)),
                ('group_title', models.CharField(max_length=255)),
                ('group_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
