# Generated by Django 3.0.7 on 2020-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economic_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_code', models.CharField(max_length=8)),
                ('group_title', models.CharField(max_length=255)),
            ],
        ),
    ]
