# Generated by Django 3.0.7 on 2020-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economic_group',
            name='group_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='economic_group',
            name='eco_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
