# Generated by Django 4.1 on 2022-08-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic_group',
            name='eco_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
