# Generated by Django 4.1 on 2022-08-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('function_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_code', models.CharField(default='00000', max_length=5, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function_groups.function_group')),
            ],
        ),
    ]
